### ISSUE TITLE
Guarded one-shot execution

### ISSUE THREAD

**Issue by dendvz** [alexey-martynov/fault-injection#1]
Would be great to have a macro which does the following in a guarded context:
- checks if injection point is active
- if yes, executes an action
- deactivates the injection point

**Comment by alexey-martynov** [comment]
Such point should be inserted like:

```c++
FAULT_INJECT_ACTION(space, point, raise_error());
```

Or, for a complex action:

```c++
FAULT_INJECT_ACTION(space, point, do { var1 = 1; var2 = 2; } while (false));
```
